//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.11 at 02:26:06 PM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.quakearts.com/workflow_assignement", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.quakearts.workflowapp.jbpm.xml.assignment;
