/*******************************************************************************
* Copyright (C) 2016 Kwaku Twumasi-Afriyie <kwaku.twumasi@quakearts.com>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Kwaku Twumasi-Afriyie <kwaku.twumasi@quakearts.com> - initial API and implementation
 ******************************************************************************/
package com.quakearts.tools.classloaders.hibernate;

import javax.persistence.Column;
import javax.persistence.ConstraintMode;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 17-Mar-2014 00:13:24 by Hibernate Tools 3.4.0.CR1

/**
 * JarFileEntry generated by hbm2java
 */
@Entity
@Table(name="jar_file_entries")
public class JarFileEntry implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1662876000076587796L;
	@Id
	@Column(name="entry_name")
	private String id;
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="jid",nullable=false,foreignKey=@ForeignKey(ConstraintMode.CONSTRAINT))
	private JarFile jarFile;

	public JarFileEntry() {
	}

	public JarFileEntry(String id, JarFile jarFile) {
		this.id = id;
		this.jarFile = jarFile;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public JarFile getJarFile() {
		return this.jarFile;
	}

	public void setJarFile(JarFile jarFile) {
		this.jarFile = jarFile;
	}

	public long getJarId() {
		return jarFile!=null?jarFile.getId():0;
	}

	public String getEntryClassName() {
		if (this.id != null) {
			return this.id.replace(".class", "").replaceAll("[\\\\/$]", ".");
		}
		return "";
	}
}
